# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ubospica/develop/cpu/Hummingbird/vivado/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/ubospica/develop/cpu/Hummingbird/vivado/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ubospica/develop/cpu/Hummingbird/vivado/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/define.vh
read_verilog -library xil_defaultlib {
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/ALU.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/Decoder.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/Dispatcher.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/ICache.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/IF.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/InstQueue.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/LSBuffer.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/LSCtrl.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/MemCtrl.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/ROB.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/RS.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/structure/RegFile.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/block_ram/block_ram.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/cpu.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/fifo/fifo.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/hci.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/ram.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/uart/uart.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/uart/uart_baud_clk.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/uart/uart_rx.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/common/uart/uart_tx.v
  /home/ubospica/develop/cpu/Hummingbird/riscv/src/riscv_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubospica/develop/cpu/Hummingbird/riscv/src/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/ubospica/develop/cpu/Hummingbird/riscv/src/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
